project:
  type: website

website:
  title: "Ashlyn Salts"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - data_analysis.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

