---
title: "About"
---

**About me**

I'm Ashlyn Salts and I've had a little bit of an interesting path to find myself in the field of public health. From Connecticut, I decided to attend college at University of Nebraska-Lincoln (Go big red!) and major in biochemistry on the pre-med track. After two years, I decided that med school wasn't for me and I couldn't imagine myself doing anything in science besides medicine. I had always liked math so actuarial science seemed like a great fit. I went on to graduate, a semester late, with a degree in actuarial science and a job offer to work at a large life insurance company. There, I realized that I was missing the health side of things. The pandemic had just hit and I found myself wondering if there was anything I could do to help. After researching various different programs/careers, I stumbled upon public health and knew that this is where I could fit. I'm passionate about ensuring everyone has access to health information to make the best decisions for themselves.